spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=SIV_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=siv_user
spring.datasource.password=TuClave123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE